; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-03-20 at 14:22:32
; total layer number: 20
; filament_density: 1.24,1.24
; filament_diameter: 1.75,1.75
; max_z_height: 10.00
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 976
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAACo0lEQVR4Ae2dPWsUURSGb2GjCCFRl+
; gqCQYEC8HCVlEsJCBaiIVr42qh+IX4gSQksBBI0iRNqlT5Kfkp+1Mm3JALh2FnZ2b33nsOzPPAKUK6
; ffa9782ZgTgHAABQ4vK9tacOdFh8+WK0dnxY3Prz9dRBPvy3fmV3a+w//DD+Z9KQgfCtrxr/ewfp6A
; 0H49WDnWKaBJ+GS9eWVh3E58b7t+PlL8Pi9ubvqRJIQyKCAD83f34u6tJAQUdGCghzZ/S/9kiioCMx
; SYCf/t/vxd2jfY6k1FQJCEfSyt42aUjJNAEyDRR0IpoIoKAT0lQABZ2ItgJCGuoKuvfh3YmDemYRQB
; oiMo8ACjoC8wpoWtDskyqIIaDpkUQaJhBTANfVGYgtgIJuSSoBFHRDUgpoU9CdTUNqAWF44FNBLgEU
; dAU5BVDQE1h6tX6aW0BIA/ukC64+ejjSkEAaSmhJ4Loq0DyS2CcJtNLAPklgOQ2dua5S0EbQ+HvBDw
; Ut0EoD+6QSGhL8sE8SUNBG0EoDBS3QSkOTF4jZJ2UYXiAWaEnguiqwXtDskxIPBS2w/MCHfRJpyAv7
; JAPwwMcIGhKaHEmkwUga2CcZSAMFnWEoaAEPfIygIcEPD3wEFLQRtNJAQQt4gdgA7JOMoCWB66qAfZ
; IRtNLAPknAddUIVtPAPinDUNACy/uk5W+fOJJST9U+qb/xq1h8vT52XcJKQfc+DorrgzfdExDQSkP/
; 34/zDz5MZwV4NNLQGw4QIMld0AioAAEGyHEkIaABCDBAqjQgoAUpChoBMxBzn4SAGVl49vgEAQZAgA
; HmKWgERAQBBmhb0AhIQJvrKgISggAD1BU0AjKBAANMSgMCMlMu6LKAKw/ujxykpyyAb74C/kjyAhae
; P+H/5QAAAFjiDIXvYZKtBw11AAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 3304
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJdUlEQVR4Ae3cy4olWRUG4IMIYmuSdK
; ut9sUsbBAcCA4soYSSLhxIg+hAHNgipBfwikgreMHEFMHUgU4cOcpHqUepR0kJ4bTV1ZlZufeJ2CvW
; iu+D/xH2z9qL2LHbAQAAAAAAAAAAAAAAAAAAABDoxW98/XwHsGZTUb3xn39dTXnlNz9/vANYo6fLap
; +Tv/3pyYc/98abO4A1mAppKqZny+rpuCIC4a6bqm6KaQsI87ypyrQFhGuZqm6KhTywuKloDi0rV0Rg
; UXNMVTfl5dPvXu4A5rBkWZm2gNkcfeXL5/f++derpQvLQh442Ee/9MXzT/30B1evn/9uWGlN09YHP/
; bSvR1Ai31hTfn0r35yNXLaOnpw/3QHcFdPF9Y+I6ctnz8Ad3ZdYU159be/HFZaFvLAndxUWBFXRAt5
; 4Fa3FdY+r/3xnaHTloU8cK27FJZpC1iFuxaWhTwQrrWw9gv5z/7778OuiBbywP/0FNb+inhycTZs2v
; IeEeguLJ8/AMMdWlgW8sAwcxRW1ELe5w+wMXMW1n7aspAHFjF3YUVMWxbysBFLFZaFPDC7JQvLQh6Y
; 1dKFFXFF9B4RihpVWKYt4GAjCyti2vIeEQqJKKwpFvJAs6jCckUEmkUW1j6jfxBo2oKk1lBYpi3gTt
; ZSWPtYyAM3Wlth7act7xGB91ljYUVMW94jQgJrLqwpPn8A3rX2wtpfES3kgRSFFXFF9B4RVihTYZm2
; YOOyFVbEtOXzB1iJrIU1xUIeNiZzYU1xRYQNyV5Y+3iPCBtQpbBMW7ABlQprHwt5KKpiYe2nLe8RoZ
; iqhbXPycXZsGnLe0RYWPXCmuLzByhiC4U1xUIeCthKYe0zeiHvPSLMaGuFtZ+2Ri7kjx7cP90Bh9ti
; YUVNWzvgMFsurCkW8pDI1gtrioU8JKGw/p/R7xEt5KGRwnpvTFuwYgrr+ljIwwoprJszLeS9R4QVUV
; i3xxURVkRh3S1+EAgroLDuHtMWBFNY7bGQhyAKqy9+EAgBFNZhGTlt+UEgm6ewDo/3iDCIwponFvIw
; gMKaNyOviN4jsjkKa/6YtmAhCmu5+PwBZqawlo2FPMxIYS0fV0SYicIaF+8R4UAKa2xMW3AAhRUTC3
; nooLDi4j0idMh0yCvGe0Ro9NI333qc6ZBXi88foEOmQ14tFvLQ4RPf+86TTAe9WkYv5L1HJD3L+NiM
; nraOHtw/3UF2mQ55xfj8ARpZyMfGQh46ZDrk1WIhDx1MW7EZ/R7RQp70LORjY9qCDpkOecVYyEMjV8
; TYTAt57xGhUaZDXi3TFfHk4swVEVqYtmLj8wfokOmQV4uFPHTwHjE2FvLQyOcPsfGDQOiQ6ZBXjB8E
; QiML+dhYyEOHTIe8WizkoYNpKzYjr4jeI1KChXxsTFvQIdMhrxifP0AjV8TYWMhDh0yHvFpcEaGDaS
; s2o38QaNoiPQv52Ji2oIP3iLGxkIdGx48eXmY65NXiPSJ0yHTIK8Z7RGhkIR8bnz9Ah0yHvFos5KGD
; hXxsvEeERj5/iI1pCzpkOuQV4/MHaGQhHxsLeeiQ6ZBXiysidDBtxcZ7RGhkIR8b0xZ0yHTIK8ZCHh
; q5IsZmWsh7jwiNMh3yijm5OBs2bXmPSAmmrdj4/AE6ZDrk1WIhDx28R4zN6IW894ik5/OH2PhBIHTI
; dMgrxucP0MhCPjYW8tAh0yGvFgt56GDaio0fBEIjC/nYmLagQ6ZDXjEW8tDIFTE2FvLQIdMhrxZXRO
; hg2oqNHwRCIwv52Ji2oIP3iLGxkIdGpq3YeI8IHTId8ooZOW35QSAlWMjHxucP0CHTIa8WC3noYNqK
; jfeI0MhCPjamLeiQ6ZBXjM8foJErYmws5KFDpkNeLa6I0MG0FRvvEaGRhXxsTFvQwXvE2FjIQyNXxN
; h4jwgdMh3yivEeERqZtmLj8wfokOmQV4uFPHSwkI/N6IW894ik5/OH2Iyeto4e3D/dQXaZDnnF+PwB
; GlnIx8ZCHjpkOuTVYiEPHUxbsRn9HtFCnvQs5GNj2oIOmQ55xVjIQyNXxNhMC3nvEaFRpkNeLa6I0M
; G0FRufP0CHTIe8Wkxb0MF7xNhYyEMjnz/Exg8CoUOmQ14xfhAIjSzkY2MhDx0yHfJqsZCHDqat2Iy8
; InqPSAkW8rExbUGHTIe8Ynz+AI1cEWNjIQ8dMh3yanFFhA6mrdiM/kGgaYv0LORjY9qCDt4jxsZCHh
; odP3p4memQV4v3iNAh0yGvGO8RoZGFfGx8/gAdMh3yarGQhw4W8rHxHhEa+fwhNqYt6JDpkFeMzx+g
; kYV8bCzkoUOmQ14trojQwbQVG+8RoZGFfGxMW9Ah0yGvGAt5aOSKGJtpIe89IjTKdMgr5uTibNi05T
; 0iJZi2YuPzB+iQ6ZBXi4U8dPAeMTajF/LeI5Kezx9iM/oHgR/6zGtv7iC7TIe8YkZMW6/+4ddXL3zh
; 8+c7qMBCPjZLLeRP/vHnq5d/+PbVx9/+tsKinkyHvFrmXshPU9VUVPsoLEoybcVmjivifqpSWGyChX
; xseqetZ6cqhcWmZDrkFdMybb3yzs9uLCuFxWa4IsbmeQv51//y+2uvgAqLTct0yKvlpivibVdAhcXm
; mbZi8/QPAu8yVSksNs9CPji/+FFTUSks2HmPGJVP/vj7Cgt6HD96eJnpsCsswEJeYUEuFvIKC9LJdP
; gVFmAhr7AgF58/KCxIJ1MZKCzAQl5hQT6ZikFhAaYthQW5WMgrLEjH5w8KC1JxRVRYkE6m0lBYgGlL
; YUE+mQpEYQEW8goLcvH5g8KCdDIVisICLOQVFuSTqVwUFrDpaUthQUJbXcgrLEgsU9koLGBTV0SFBU
; VkKh6FBZSfthQWFFN5Ia+woKiK7xEVFhRWbdpSWLABmUpJYQElFvIKCzYmU0EpLCDttKWwYKMyLuQV
; FmycwgJSyXJFVFjAuxQWkMqapy2FBbzPWhfyCgu40dreIyos4FbHjx5eKiwgFYUFpBK9kFdYQDOFBa
; QSsZBXWEC30Z8/KCzgYAoLSGXEQl5hAbNSWEAqS01bCgtYxBILeYUFLEphAanMdUVUWMAwCgtI5ZBp
; S2EBIRQWkErre8SewlJWwGxaPn9oKawXv/XWkx3AEuYsLGUFLO55C/nnFZaiAobrKSxlBYS5btq6qb
; As1oFwzy7kny0sUxWwOtcV1vHXvvp4B7BG0xVxKixTFZDCBz7ywr0dAAAAAAAAAAAAAAAAAAAAAIH+
; CzU5CO+U0x0QAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; first layer extrusion width = 1.00mm

; EXECUTABLE_BLOCK_START
M73 P0 R1
M201 X1000 Y1000 Z1000 E1000
M203 X50 Y50 Z50 E100
M204 P1000 R1000 T1000
M205 X10.00 Y10.00 Z2.00 E2.50 ; sets the jerk limits, mm/sec
;TYPE:Custom
M220 S100 ;Reset feed rate 
M221 S100 ;Reset flow rate 

M140 S55 ;Set final bed temp
G28 ;Home 
G92 E0 ;Reset extruder 
G1 Z2.0 F3000 ;Move Z Axis up 
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position 
M190 S55 ;Wait for bed temp to stabilize
M109 S220 ;Wait for nozzle temp to stabilize
G92 E0 ;Reset extruder 
G1 E-1.0000 F1800 ;Retract a bit 
G1 Z2.0 F3000 ;Move Z Axis up 
G1 E0.0000 F1800
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S255


T0
M106 S0
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;0.5
G92 E0

G1 E-.8 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 F3000
G1 Z.5
M73 P1 R1
G1 Z.5
G1 E.8 F2400
;TYPE:Outer wall
;WIDTH:1
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P4 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P6 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
M106 S255
;LAYER_CHANGE
;Z:1
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;1
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z1 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P8 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P10 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:1.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;1.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z1.5 F3000
M73 P11 R1
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P13 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P15 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:2
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z2 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P17 R1
G1 X1.262 Y-18.699 E7.23725
M73 P18 R1
G1 X2.162 Y-18.699 E.16701
M73 P20 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:2.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;2.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z2.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P22 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P24 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:3
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;3
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z3 F3000
G1 E.8 F2400
M73 P25 R1
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P27 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P29 R1
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:3.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;3.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z3.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P31 R1
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P34 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:4
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z4 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P36 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P38 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:4.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;4.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z4.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P41 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P43 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P45 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P47 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
M73 P48 R0
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:5.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;5.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z5.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P50 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P52 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:6
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z6 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P54 R0
G1 X1.262 Y-18.699 E7.23725
M73 P55 R0
G1 X2.162 Y-18.699 E.16701
M73 P57 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:6.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;6.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z6.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P59 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P61 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:7
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;7
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z7 F3000
G1 E.8 F2400
M73 P62 R0
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P64 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P66 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:7.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;7.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z7.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P68 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P71 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:8
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;8
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z8 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P73 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P75 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:8.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;8.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z8.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P78 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P80 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:9
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;9
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z9 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P82 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P84 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
M73 P85 R0
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:9.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;9.5
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z9.5 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P87 R0
G1 X1.262 Y-18.699 E7.23725
G1 X2.162 Y-18.699 E.16701
M73 P89 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
;LAYER_CHANGE
;Z:10
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;10
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:15 copy 0
G1 X2.262 Y-18.699 Z10 F3000
G1 E.8 F2400
G1 F1225
G1 X2.262 Y20.301 E7.23725
G1 X1.262 Y20.301 E.18557
M73 P91 R0
G1 X1.262 Y-18.699 E7.23725
M73 P92 R0
G1 X2.162 Y-18.699 E.16701
M73 P94 R0
; stop printing object Cube id:15 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F3000
G1 X2.165 Y-17.699 E-.24
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode 
M106 P3 S0
G91 ;Relative positioning 
G1 E-2 F2700 ;Retract a bit 
G1 E-2 Z0.2 F2400 ;Retract and raise Z 
G1 X5 Y5 F3000 ;Wipe out 
G1 Z3 ;Raise Z more 
G90 ;Absolute positioning 
G1 X2 Y218 F3000 ;Present print 
M106 S0 ;Turn-off fan 
M104 S0 ;Turn-off hotend 
M140 S0 ;Turn-off bed 
M84 X Y E ;Disable all steppers but Z
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 296.54, 0.00
; filament used [cm3] = 0.71, 0.00
; filament used [g] = 0.88, 0.00
; filament cost = 0.02, 0.00
; total filament used [g] = 0.88
; total filament cost = 0.02
; total layers count = 20
; estimated printing time (normal mode) = 1m 29s
; estimated first layer printing time (normal mode) = 1s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0,0
; activate_chamber_temp_control = 0,0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0,0
; adaptive_pressure_advance_bridges = 0,0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0";"0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0,0
; additional_cooling_fan_speed = 70,70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0,0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1,1
; complete_print_exhaust_fan_speed = 70,70
; cool_plate_temp = 35,30
; cool_plate_temp_initial_layer = 35,30
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 0
; default_bed_type = 
; default_filament_colour = ;
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Creality CR10SE 0.8
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = ;;;gcode_flavor;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_acceleration_z;machine_max_speed_x;machine_max_speed_y;machine_max_speed_z;machine_start_gcode;max_layer_height;min_layer_height;printable_area;z_hop
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0,0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70,70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1,1
; enable_overhang_speed = 1
; enable_pressure_advance = 0,0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0,30
; eng_plate_temp_initial_layer = 0,30
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A;#00C1AE
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100,100
; fan_kickstart = 0
; fan_max_speed = 100,100
; fan_min_speed = 100,100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A;#00C1AE
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 20,20
; filament_density = 1.24,1.24
; filament_diameter = 1.75,1.75
; filament_end_gcode = "; filament end gcode \nM106 P3 S0\n";"; filament end gcode\n"
; filament_flow_ratio = 1,1
; filament_ids = P510eff9;OGFU99
; filament_is_support = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 200,3.2
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_multitool_ramming = 0,0
; filament_multitool_ramming_flow = 10,10
; filament_multitool_ramming_volume = 10,10
; filament_notes = ;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retraction_length = nil,0.4
; filament_settings_id = "Generic PLA template @Creality Creality CR-10 V2 1.0 nozzle";"Generic TPU @System"
; filament_shrink = 100%,100%
; filament_shrinkage_compensation_z = 100%,100%
; filament_soluble = 0,0
; filament_stamping_distance = 0,0
; filament_stamping_loading_speed = 0,0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}";"; Filament gcode\n"
; filament_toolchange_delay = 0,0
; filament_type = PLA;TPU
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Generic;Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0,89,60,0
; flush_volumes_vector = 140,140,140,140
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 50
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55,35
; hot_plate_temp_initial_layer = 55,35
; idle_temperature = 0,0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = ;;;"Creality Creality CR-10 V2 1.0 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 50
; initial_layer_jerk = 9
; initial_layer_line_width = 1
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.5
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_jerk = 9
; inner_wall_line_width = 1
; inner_wall_speed = 50
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1,-1
; internal_bridge_flow = 1
; internal_bridge_speed = 100%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 1
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 50
; ironing_angle = -1
; ironing_fan_speed = -1,-1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.5
; line_width = 1
; long_retractions_when_cut = 0
; machine_end_gcode = G91 ;Relative positioning \nG1 E-2 F2700 ;Retract a bit \nG1 E-2 Z0.2 F2400 ;Retract and raise Z \nG1 X5 Y5 F3000 ;Wipe out \nG1 Z3 ;Raise Z more \nG90 ;Absolute positioning \nG1 X2 Y218 F3000 ;Present print \nM106 S0 ;Turn-off fan \nM104 S0 ;Turn-off hotend \nM140 S0 ;Turn-off bed \nM84 X Y E ;Disable all steppers but Z
; machine_load_filament_time = 0
; machine_max_acceleration_e = 1000,5000
; machine_max_acceleration_extruding = 1000,5000
; machine_max_acceleration_retracting = 1000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 1000,8000
; machine_max_acceleration_y = 1000,8000
; machine_max_acceleration_z = 1000,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 2,2
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 100,100
; machine_max_speed_x = 50,600
; machine_max_speed_y = 50,600
; machine_max_speed_z = 50,30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25
; machine_start_gcode = M220 S100 ;Reset feed rate \nM221 S100 ;Reset flow rate \n\nM140 S[bed_temperature_initial_layer_single] ;Set final bed temp\nG28 ;Home \nG92 E0 ;Reset extruder \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position \nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG92 E0 ;Reset extruder \nG1 E-1.0000 F1800 ;Retract a bit \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 E0.0000 F1800
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.8
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.2
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220,240
; nozzle_temperature_initial_layer = 220,240
; nozzle_temperature_range_high = 240,250
; nozzle_temperature_range_low = 190,200
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 1
; outer_wall_speed = 50
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100,100
; overhang_fan_threshold = 50%,95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157,0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02,0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Creality Creality CR-10 V2 1.0 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = process template @Creality Creality CR-10 V2 1.0 nozzle
; printable_area = -162.5x-162.5,162.5x-162.5,162.5x162.5,-162.5x162.5
; printable_height = 200
; printer_model = Creality Creality CR-10 V2
; printer_notes = 
; printer_settings_id = robot arm
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 1.0
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1,1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3,3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1,1
; slow_down_layer_time = 4,8
; slow_down_layers = 0
; slow_down_min_speed = 20,10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 10%
; sparse_infill_filament = 1
; sparse_infill_line_width = 1
; sparse_infill_pattern = grid
; sparse_infill_rotate_template = 
; sparse_infill_speed = 50
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35,0
; supertack_plate_temp_initial_layer = 35,0
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 1
; support_material_interface_fan_speed = -1,-1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 55,30
; template_custom_gcode = 
; textured_cool_plate_temp = 40,40
; textured_cool_plate_temp_initial_layer = 40,40
; textured_plate_temp = 55,35
; textured_plate_temp_initial_layer = 55,35
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 1
; top_surface_pattern = monotonic
; top_surface_speed = 50
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 50
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 4.000
; wipe_tower_x = 4
; wipe_tower_y = 158.500
; wipe_tower_y = 158.5
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = -162.5x-162.5,162.5x-162.5,162.5x162.5,-162.5x162.5
; first_layer_temperature = 220
; first_layer_height = 0.500
; CONFIG_BLOCK_END


