; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-03-16 at 12:14:45
; total layer number: 1
; filament_density: 1.24,1.24
; filament_diameter: 1.75,1.75
; max_z_height: 0.50
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 924
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAACe0lEQVR4Ae2csUokQRRFK9hkYQV3hx
; XWRZQVNt/ABY1EAw3URBONJjJQNBE1URkQ1EQTIyM/ZT5lPkWtoLGDrunumqrqelXnwE1kknrc9275
; umeUAgAAAAAAAAAAAACAcXzf2hh8/bu4qiA8uviLL09vWjP9/VcF4Zi/uxoVxS+k/0Y3eKbsepP0Zx
; S4p8r1JunPfun9WFAwOU1cTzd4YpLiF5o9OxoqaIcO0zYjp8lIIqAb4sL1jCRLXLqebmiBT9fTDTXo
; /2JDF5+A/mBqeakfYuQwkiroYuTUKZt9Ugyuz7IbYnS9SckFtA47KcUvd4P4fZIk15ukLwtKIikUv5
; C462rMQWsrEQGdkutNijagU3T9uG6IJqBzcH203ZBz8Qt1EtCuH5hIV9CAxvVmed8n4fp6eekGXN9e
; zgJa4h4nFunaWV9Xcb0bWY0kiu9ejQOaoPWnsd2A68OpcsU9tfJ/sPB4K+ogEqW74NvSv4FxBM2eHY
; 8kHUiSfp0ejlQTpjfWXv88P4g6XOwa63oTc4NLUYeMUY1db+Lnwd5Q0oGTKn4ZArq55m7O/TywIaDr
; 5dT1VXBdNcsqaG0hoD/l3fUmCOint97udvfvDOU4kn5fnHTjehMz/YOhpAJOos5GTh05BHTQoLUlxY
; CO1vUmens7w1T2SdOb63K/PSO5G8S53oTE62oyxS8jIaCT/6WVmPdJSbq+ihivqyKul66JIaCzcb2J
; LgM6++KXCTmSvD0wkU6IfRKur8FnQGcZtLa4DGhcb4kO6En3SVE8MJHO/P01ru+aNtdViu+JuoCuff
; EV3FC1T8L1gSm/QIzrAQAAAAAAAAAAAAAgZt4BezjMLRO+qU4AAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2800
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAH+klEQVR4Ae3dQWsdVRiA4btwo0RLq5
; aaGlIMCAoFFxHiomJxIQXRhbiwbmo32iIiUTCKxQTB6kI3rlzlp/Sn9KdEJnYkbXNz7505M3O+c54H
; 3o24adoO3/mYM53NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAIb/O3nx82PfPihSszgByd//CD/a1//jo6WfPfZgA5Oe1h1bb+3d0HM4CpPfv61nvN
; 8W/ew6qt+X+a/3cGMIWzpqp5OSICo1tmqjJtAZPqMlWZtoDRXbz12WGqh5WFPDCI5995+1bqB5UjIp
; BcyiPgopoJbgbQRZ/FumkLGMWYU9WWhTzQVbMEn/phdXLach8ReEoOU5VpC1go54dVm9cfgEkW632O
; iBbyUKEIU9WWIyIQaaoybUGlIk9Vpi2oSIkPqzYLeSjEsh/Yi54jIgRX8lQ1L/cRIaAapirTFgRX41
; Q1Lwt5yFhO9wBzqfmZuI8IGTFVnV1zRGw+QjgDpuVhtXxef4AJ1bxY75qFPIzMVNU/C3kYgakqXT4Q
; CAMxVQ2XaQsS8rAaPgt56KmWe4C5ZCEPHZmqpssREVZgqpo+0xYsYKrKL9MWnMI9wHyzkIdHmjtukf
; 7y1pojItVzBIyXDwRSJYv1uJm2qIapqpws5CmaxXp5uY9IcUxV5WfaoggeVvXk9QdCs1ivLwt5wjFV
; yRGREExVajNtkS1TleZl2iIrzdvPkf4Cafws5JmcD+xplRwRmYwjoLrmPiKjMlWpb6YtBmeqUuos5B
; mEe4AaqubPlvuIJGGq0lg1H3OcQVceVho7rz/QicW6pspCnqWZqpRLFvKcyVSl3PKBQJ5iqlLumbY4
; 5mGlKFnIV8w9QEXMQr5CpipFzxGxEqYqlZJpq2CmKpWaaasw7gGq9CzkC2CqUk05IgbmYaVa84HAYC
; zWVXumrQBMVdLjWchnylQlnZ77iBkxVUnLZdqamIeVtFpef5iAe4BS9yzkR2SqktLkiDgwU5WUNtPW
; AExV0rCZthJp3tqN9BsvRc1Cvofm32iL9JstlZAjYgeOgNK0uY+4JIt1KY9MW2cwVUl5ZiH/BB/Yk/
; LOfcSZqUqKVrXTloeVFLPqXn+wWJdiV8VC3lQllVWxR0RTlVRmRU1bpiqpjsJPWx5WUl2FXMj7wJ5U
; b6GOiKYqSU3Z30c0VUk6WZbTlqlK0llls5B3D1DSMjXPisnuI5qqJK3aJEdEDytJfRrt9QeLdUkpGn
; TaMlVJGqLkC3lTlaQhS/KBQFOVpDHrPG09d/VN/8yWpNF74drO/mxVa9tv7b/yzZdHV/78NdQvVlLM
; Ng72ji7evnn03NU39mddXfrqi6NXf9oN9QuXFKvLP357dP7jGw9nKVz46MYD05akIWqmqmQPq1ZzRG
; ymrY39H0L9MCTlWTtV9ToCLvLy558+bKat1/7+PdQPR1I+Xbp7O/1UNU9zRDRtSVq1Zqp66eYnR4NO
; VfM0D63L338d6gcmaZqSLta7spCXtKhBFut9OCJKerIspqp52oW8aUtSdlPVabz+INXdpIv1rizkpf
; rK+gi4iIW8VEebf/xyfAQ89/678f4h1Se5jyiVW+ipah7TllReIRbrXVnIS2UUcrHeVbuQdx9Riteo
; 9wBz4YgoxaqdqtZ2tg9ntfL6g5R/RS7WuzJtSflW9GK9Dwt5KZ9MVUvwgUBp+kxVK/D6gzRNVb2ukJ
; qFvDRejoAJWMhLw9beA/SwSsgRUUqfqWpApi0pXaaqEVjIS/2yWJ+Ahby0euu7d0xVU3FElJZr42Dv
; eKoq4gN70flAoDQ/i/UMmbakp7NYz5iFvPRf7VRlsR6A+4iquSo/sBfduevXDk1bqimvKxTA6w+qIY
; v1gljIq+Qs1gvliKiSMlVVoF3Im7YUOVNVRbz+oKhZrFfMQl6RcgTEQl7Z135gzz1A/uc+onLMVMVc
; pi3llMU6C1nIa+rcA2Rl7ULefUSNmXuAdNYeETfv3wv1h17xal9XWNvZPpxBH15/0JBZrJOchbyGyG
; KdQVnIK0WmKkbjA4Hqk6mK0Xn9QavmHiCTs5DXMjkCkg0Lec2rvQfoYUV2HBF1MlMV2TNtqclURRgW
; 8vVmsU5YFvJ15R4g4Tkilt/Gwd7xVOUDexTDBwLLzGKdYpm2yspineJZyMfPB/aojvuIMbNYp1rnrl
; 87NG3FyOsK8IjXH/J/WJmq4AQL+fxyDxAWcETMI1MVLKldyJu2pslUBSvy+sP4WaxDTxby47S+e8dU
; BSlYyA9Xu1h3DxAScx8xbRbrMDDTVpos1mEkFvLdcw8QJtK8/tAs5N1HXC73AGFizRGxmbY2798L9f
; AYM68rQGa8/jD/YWWqggxZyD+exToEUPtC3lQFwdT6gUBTFQRV0+sPFutQiNIX8o6AUJgSF/LuAULh
; SjkimqqgEtGnLYt1qEzEhbzFOlQuykLePUDgWM5HxHaqWtvZPpwBtHL7QKDFOnCmXKYti3VgKVMu5H
; 1gD+hk7PuIpiqglzGmLa8rAEkN9fqDxTowiJQL+fYeoIcVMKi+R0RTFTCqrtOWqQqYxCoLeYt1IAuL
; FvLru3dMVUA+Tjsibhzs+cAekK/2PqLFOhBCM215WAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlOFfmSh3FSxF7GUAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; first layer extrusion width = 1.00mm

; EXECUTABLE_BLOCK_START
M73 P0 R1
M201 X8000 Y8000 Z500 E5000
M203 X200 Y200 Z30 E100
M204 P5000 R5000 T5000
M205 X10.00 Y10.00 Z2.00 E2.50 ; sets the jerk limits, mm/sec
;TYPE:Custom
M220 S100 ;Reset feed rate 
M221 S100 ;Reset flow rate 

M140 S55 ;Set final bed temp
M104 S230 ;Set hotend temp
G28 ;Home 
G92 E0 ;Reset extruder 
G1 Z2.0 F3000 ;Move Z Axis up 
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position 
M190 S55 ;Wait for bed temp to stabilize
M109 S220 ;Wait for nozzle temp to stabilize
G92 E0 ;Reset extruder 
G1 E-1.0000 F1800 ;Retract a bit 
G1 Z2.0 F3000 ;Move Z Axis up 
G1 E0.0000 F1800
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S255


T0
M106 S0
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;0.5
G92 E0

G1 E-.8 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
M204 S500
; printing object Cube id:0 copy 0
G1 Z.9 F30000
G1 X19.963 Y19.35
G1 Z.9
M73 P1 R1
G1 Z.5
G1 E.8 F2400
;TYPE:Outer wall
;WIDTH:1
G1 F1613.086
G1 X-18.737 Y19.35 E7.18158
G1 X-18.737 Y-19.35 E7.18158
M73 P3 R1
G1 X19.963 Y-19.35 E7.18158
M73 P5 R1
G1 X19.963 Y19.25 E7.16302
M73 P7 R1
G1 E-.56 F1800
M73 P9 R1
;WIPE_START
G1 F1613.086
G1 X18.963 Y19.253 E-.24
;WIPE_END
G1 Z.9 F30000
G1 X19.695 Y-17.259 Z.9
G1 Z.5
G1 E.8 F2400
M73 P10 R1
;TYPE:Bottom surface
;WIDTH:1.00895
G1 F1597.078
G1 X18.273 Y-18.68 E.37686
G1 X16.998 Y-18.68 E.239
G1 X19.293 Y-16.385 E.60838
G1 X19.293 Y-15.11 E.239
G1 X15.723 Y-18.68 E.94637
G1 X14.448 Y-18.68 E.239
G1 X19.293 Y-13.835 E1.28436
G1 X19.293 Y-12.56 E.239
M73 P11 R1
G1 X13.173 Y-18.68 E1.62235
G1 X11.898 Y-18.68 E.239
G1 X19.293 Y-11.285 E1.96035
G1 X19.293 Y-10.01 E.239
M73 P12 R1
G1 X10.623 Y-18.68 E2.29834
G1 X9.348 Y-18.68 E.239
M73 P13 R1
G1 X19.293 Y-8.735 E2.63633
G1 X19.293 Y-7.459 E.239
M73 P14 R1
G1 X8.072 Y-18.68 E2.97432
G1 X6.797 Y-18.68 E.239
G1 X19.293 Y-6.184 E3.31232
M73 P15 R1
G1 X19.293 Y-4.909 E.239
G1 X5.522 Y-18.68 E3.65031
M73 P16 R1
G1 X4.247 Y-18.68 E.239
M73 P17 R1
G1 X19.293 Y-3.634 E3.9883
G1 X19.293 Y-2.359 E.239
M73 P18 R1
G1 X2.972 Y-18.68 E4.32629
G1 X1.697 Y-18.68 E.239
M73 P19 R1
G1 X19.293 Y-1.084 E4.66429
G1 X19.294 Y.191 E.239
M73 P20 R1
G1 X.422 Y-18.68 E5.00228
G1 X-.853 Y-18.68 E.239
M73 P22 R0
G1 X19.294 Y1.466 E5.34027
G1 X19.294 Y2.742 E.239
M73 P23 R0
G1 X-2.128 Y-18.68 E5.67826
G1 X-3.404 Y-18.68 E.239
M73 P25 R0
G1 X19.294 Y4.017 E6.01626
G1 X19.294 Y5.292 E.239
M73 P27 R0
G1 X-4.679 Y-18.68 E6.35425
G1 X-5.954 Y-18.68 E.239
M73 P29 R0
G1 X19.294 Y6.567 E6.69224
G1 X19.294 Y7.842 E.239
M73 P30 R0
G1 X-7.229 Y-18.68 E7.03023
M73 P31 R0
G1 X-8.504 Y-18.68 E.239
M73 P32 R0
G1 X19.294 Y9.117 E7.36823
G1 X19.294 Y10.392 E.239
M73 P34 R0
G1 X-9.779 Y-18.68 E7.70622
M73 P35 R0
G1 X-11.054 Y-18.68 E.239
M73 P37 R0
G1 X19.294 Y11.667 E8.04421
G1 X19.294 Y12.942 E.239
M73 P39 R0
G1 X-12.329 Y-18.68 E8.3822
G1 X-13.605 Y-18.68 E.239
M73 P41 R0
G1 X19.294 Y14.218 E8.7202
G1 X19.294 Y15.493 E.239
M73 P44 R0
G1 X-14.88 Y-18.68 E9.05819
G1 X-16.155 Y-18.68 E.239
M73 P46 R0
G1 X19.294 Y16.768 E9.39618
G1 X19.294 Y18.043 E.239
M73 P49 R0
G1 X-17.43 Y-18.68 E9.73417
G1 X-18.067 Y-18.68 E.11949
M73 P52 R0
G1 X-18.067 Y-18.043 E.11951
G1 X18.656 Y18.68 E9.73414
G1 X17.381 Y18.68 E.239
M73 P54 R0
G1 X-18.067 Y-16.768 E9.39615
G1 X-18.067 Y-15.493 E.239
M73 P57 R0
G1 X16.106 Y18.68 E9.05815
G1 X14.831 Y18.68 E.239
M73 P59 R0
G1 X-18.067 Y-14.217 E8.72016
G1 X-18.067 Y-12.942 E.239
M73 P62 R0
G1 X13.555 Y18.68 E8.38217
G1 X12.28 Y18.68 E.239
M73 P64 R0
G1 X-18.067 Y-11.667 E8.04418
G1 X-18.067 Y-10.392 E.239
M73 P66 R0
G1 X11.005 Y18.68 E7.70618
G1 X9.73 Y18.68 E.239
M73 P69 R0
G1 X-18.067 Y-9.117 E7.36819
G1 X-18.067 Y-7.842 E.239
M73 P71 R0
G1 X8.455 Y18.68 E7.0302
G1 X7.18 Y18.68 E.239
M73 P73 R0
G1 X-18.067 Y-6.567 E6.69221
G1 X-18.067 Y-5.292 E.239
M73 P75 R0
G1 X5.905 Y18.68 E6.35421
G1 X4.63 Y18.68 E.239
M73 P76 R0
G1 X-18.067 Y-4.017 E6.01622
G1 X-18.067 Y-2.741 E.239
M73 P78 R0
G1 X3.354 Y18.68 E5.67823
G1 X2.079 Y18.68 E.239
M73 P80 R0
G1 X-18.067 Y-1.466 E5.34024
G1 X-18.067 Y-.191 E.239
M73 P81 R0
G1 X.804 Y18.68 E5.00224
G1 X-.471 Y18.68 E.239
M73 P83 R0
G1 X-18.067 Y1.084 E4.66425
G1 X-18.067 Y2.359 E.239
M73 P84 R0
G1 X-1.746 Y18.68 E4.32626
G1 X-3.021 Y18.68 E.239
M73 P85 R0
G1 X-18.067 Y3.634 E3.98827
G1 X-18.067 Y4.909 E.239
M73 P86 R0
G1 X-4.296 Y18.68 E3.65027
M73 P87 R0
G1 X-5.571 Y18.68 E.239
M73 P88 R0
G1 X-18.067 Y6.184 E3.31228
G1 X-18.067 Y7.46 E.239
M73 P89 R0
G1 X-6.847 Y18.68 E2.97429
G1 X-8.122 Y18.68 E.239
G1 X-18.067 Y8.735 E2.6363
M73 P90 R0
G1 X-18.067 Y10.01 E.239
G1 X-9.397 Y18.68 E2.2983
G1 X-10.672 Y18.68 E.239
M73 P91 R0
G1 X-18.067 Y11.285 E1.96031
G1 X-18.067 Y12.56 E.239
M73 P92 R0
G1 X-11.947 Y18.68 E1.62232
G1 X-13.222 Y18.68 E.239
G1 X-18.067 Y13.835 E1.28433
G1 X-18.067 Y15.11 E.239
M73 P93 R0
G1 X-14.497 Y18.68 E.94633
G1 X-15.772 Y18.68 E.239
G1 X-18.067 Y16.385 E.60834
G1 X-18.067 Y17.661 E.239
G1 X-16.646 Y19.082 E.37683
; stop printing object Cube id:0 copy 0
G1 E-.56 F1800
M73 P94 R0
;WIPE_START
G1 F1597.078
G1 X-17.353 Y18.375 E-.24
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode 
M106 P3 S0
G91 ;Relative positioning 
G1 E-2 F2700 ;Retract a bit 
G1 E-2 Z0.2 F2400 ;Retract and raise Z 
G1 X5 Y5 F3000 ;Wipe out 
G1 Z3 ;Raise Z more 
G90 ;Absolute positioning 
G1 X2 Y218 F3000 ;Present print 
M106 S0 ;Turn-off fan 
M104 S0 ;Turn-off hotend 
M140 S0 ;Turn-off bed 
M84 X Y E ;Disable all steppers but Z
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 332.67, 0.00
; filament used [cm3] = 0.80, 0.00
; filament used [g] = 0.99, 0.00
; filament cost = 0.02, 0.00
; total filament used [g] = 0.99
; total filament cost = 0.02
; total layers count = 1
; estimated printing time (normal mode) = 1m 15s
; estimated first layer printing time (normal mode) = 1s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0,0
; activate_chamber_temp_control = 0,0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0,0
; adaptive_pressure_advance_bridges = 0,0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0";"0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0,0
; additional_cooling_fan_speed = 70,70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0,0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1,1
; complete_print_exhaust_fan_speed = 70,70
; cool_plate_temp = 35,30
; cool_plate_temp_initial_layer = 35,30
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_bed_type = 
; default_filament_colour = ;
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Creality CR10SE 0.8
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = inner_wall_speed;internal_solid_infill_pattern;outer_wall_speed;sparse_infill_pattern;;;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0,0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70,70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1,1
; enable_overhang_speed = 1
; enable_pressure_advance = 0,0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0,30
; eng_plate_temp_initial_layer = 0,30
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A;#00C1AE
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100,100
; fan_kickstart = 0
; fan_max_speed = 100,100
; fan_min_speed = 100,100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A;#00C1AE
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 20,20
; filament_density = 1.24,1.24
; filament_diameter = 1.75,1.75
; filament_end_gcode = "; filament end gcode \nM106 P3 S0\n";"; filament end gcode\n"
; filament_flow_ratio = 1,1
; filament_ids = P510eff9;OGFU99
; filament_is_support = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 12,3.2
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_multitool_ramming = 0,0
; filament_multitool_ramming_flow = 10,10
; filament_multitool_ramming_volume = 10,10
; filament_notes = ;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retraction_length = nil,0.4
; filament_settings_id = "Generic PLA template @RA3D printer model 1 1.0 nozzle";"Generic TPU @System"
; filament_shrink = 100%,100%
; filament_shrinkage_compensation_z = 100%,100%
; filament_soluble = 0,0
; filament_stamping_distance = 0,0
; filament_stamping_loading_speed = 0,0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}";"; Filament gcode\n"
; filament_toolchange_delay = 0,0
; filament_type = PLA;TPU
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Generic;Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0,89,60,0
; flush_volumes_vector = 140,140,140,140
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55,35
; hot_plate_temp_initial_layer = 55,35
; idle_temperature = 0,0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 1
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.5
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_jerk = 9
; inner_wall_line_width = 1
; inner_wall_speed = 100
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1,-1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 1
; internal_solid_infill_pattern = rectilinear
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_fan_speed = -1,-1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.5
; line_width = 1
; long_retractions_when_cut = 0
; machine_end_gcode = G91 ;Relative positioning \nG1 E-2 F2700 ;Retract a bit \nG1 E-2 Z0.2 F2400 ;Retract and raise Z \nG1 X5 Y5 F3000 ;Wipe out \nG1 Z3 ;Raise Z more \nG90 ;Absolute positioning \nG1 X2 Y218 F3000 ;Present print \nM106 S0 ;Turn-off fan \nM104 S0 ;Turn-off hotend \nM140 S0 ;Turn-off bed \nM84 X Y E ;Disable all steppers but Z
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 5000,5000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 8000,8000
; machine_max_acceleration_y = 8000,8000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 2,2
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 100,100
; machine_max_speed_x = 200,600
; machine_max_speed_y = 200,600
; machine_max_speed_z = 30,30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25
; machine_start_gcode = M220 S100 ;Reset feed rate \nM221 S100 ;Reset flow rate \n\nM140 S[bed_temperature_initial_layer_single] ;Set final bed temp\nG28 ;Home \nG92 E0 ;Reset extruder \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position \nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG92 E0 ;Reset extruder \nG1 E-1.0000 F1800 ;Retract a bit \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 E0.0000 F1800
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.64
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.16
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220,240
; nozzle_temperature_initial_layer = 220,240
; nozzle_temperature_range_high = 240,250
; nozzle_temperature_range_low = 190,200
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 1
; outer_wall_speed = 100
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100,100
; overhang_fan_threshold = 50%,95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157,0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02,0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "RA3D printer model 1 1.0 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = process template @RA3D printer model 1 1.0 nozzle
; printable_area = -100x-100,100x-100,100x100,-100x100
; printable_height = 130
; printer_model = RA3D printer model 1
; printer_notes = 
; printer_settings_id = RA3D printer model 1 1.0 nozzle
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 1.0
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1,1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3,3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1,1
; slow_down_layer_time = 4,8
; slow_down_layers = 0
; slow_down_min_speed = 20,10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 1
; sparse_infill_pattern = grid
; sparse_infill_rotate_template = 
; sparse_infill_speed = 270
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35,0
; supertack_plate_temp_initial_layer = 35,0
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 1
; support_material_interface_fan_speed = -1,-1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 55,30
; template_custom_gcode = 
; textured_cool_plate_temp = 40,40
; textured_cool_plate_temp_initial_layer = 40,40
; textured_plate_temp = 55,35
; textured_plate_temp_initial_layer = 55,35
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 1
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 4.000
; wipe_tower_x = 4
; wipe_tower_y = 96.000
; wipe_tower_y = 96
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = -100x-100,100x-100,100x100,-100x100
; first_layer_temperature = 220
; first_layer_height = 0.500
; CONFIG_BLOCK_END


